# Generated by Django 5.2.1 on 2025-05-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="client",
            table="client",
        ),
    ]
