# Generated by Django 5.2.1 on 2025-05-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Type_of_mood",
            new_name="TypeOfMood",
        ),
        migrations.AlterField(
            model_name="mood",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
