# Generated by Django 5.2.1 on 2025-05-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_rename_type_of_mood_typeofmood_alter_mood_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="note",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
