# Generated by Django 5.2.1 on 2025-05-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_mood_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="date",
            field=models.CharField(max_length=120),
        ),
    ]
